import Head from 'next/head'
import { Inter } from '@next/font/google'
import Avator from '@/components/Avator'
// import { MicrophoneIcon } from '@heroicons/react/24/solid'
import { BsFillGridFill } from 'react-icons/bs'
import Image from 'next/image'
import { MicrophoneIcon, SearchIcon } from '@heroicons/react/outline'
import Footer from '@/components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'


function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div
      className='flex flex-col items-center justify-center h-screen'
    >
      <Head>
        <title>Gugal.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* change the icon */}
      </Head>

      {/* header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>

        {/* left sction */}
        <div className='flex space-x-4 items-center'>
          <p className='hover:underline cursor-pointer'>about</p>
          <p className='hover:underline cursor-pointer'>store</p>
        </div>

        {/* right sction */}
        <div className='flex space-x-4 items-center'>
          <p className='hover:underline cursor-pointer'>gmail</p>
          <p className='hover:underline cursor-pointer'>images</p>

          {/* icon */}
          <BsFillGridFill className='h-10 width-10 rounded-full hover:bg-gray-100 cursor-pointer' />

          {/* AVATAR */}
          <Avator url='https://avatars.githubusercontent.com/u/113396637?v=4' />

        </div>

      </header>

      {/* body */}

      <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
        <Image
          src='https://cdn.freebiesupply.com/logos/large/2x/google-1-1-logo-png-transparent.png'
          height={100}
          width={300}
        />
        <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon
            className='h-5 mr-3 text-gray-500'
          />
          <input ref={searchInputRef}
            className='focus:outine-none flex-grow ' type='search' placeholder='Search' />
          <MicrophoneIcon className='h-5 text-gray-500' />
        </div>

        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} type='submit' className='btn hover:ring1 cursor-pointer focus: outline-none active:ring-gray-300 hover:shadow-md'>Google Search</button>
          <button onClick={search} type='submit' className='btn hover:ring1 cursor-pointer focus: outline-none active:ring-gray-300 hover:shadow-md'>I'm Feeling Lucky</button>
        </div>
      </form>

      {/* footer */}

      <Footer />

    </div>
  )
}

export default Home;
